//Script generated by SceneScriptGenerator.cs

namespace StorkStudios.CoreNest
{
	public enum Scene
	{
		Intro = 0,
		SampleScene = 1,
	}
	
	public static class SceneExtensions
	{
		public static int GetBuildIndex(this Scene value)
		{
			return (int)value;
		}
	}
}
